version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\v2rayN\v2rayN
before_build:
- cmd: nuget restore
build:
  verbosity: normal
artifacts:
- path: v2rayN\v2rayN\bin\4.5\Release\v2rayN.exe
  name: v2rayN.exe
