version: 1.0.{build}
image: Visual Studio 2015
environment:
  matrix:    
    - platform: Any CPU
      configuration: Release
matrix:
  fast_finish: false
build:
  parallel: true
  verbosity: normal
artifacts:
- path: v2rayN\bin\Release\v2rayN.exe
  name: v2rayN.exe
